### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by kousu**
Fixes https://github.com/neuropoly/intranet.neuro.polymtl.ca/issues/23 (I know that that's in the other repo :shrug:)

### CODE REVIEW

**Review by jcohenadad — COMMENTED** [review]
Thank you @kousu 
i suppose we also need to add an entry in the TOC

**Comment by kousu** [comment]
Hang on, is there a pre-existing policy somewhere? Was there something on the old site?
 
I blindly copy-pasted the most common CoC thinking it would apply to the wiki(s) itself; like, the abstract space of code. But **putting it on the ToC** implies it's wider than I thought. There must be university policy that we need to make sure it's compatible with.

I'm not that comfortable with just pasting this on top without knowing we can mean it. We need to know what procedures would be in place to actually enforce it, and what parts intersect with university admin.

A lot of the examples in https://github.com/neuropoly/intranet.neuro.polymtl.ca/issues/25#issuecomment-973334320 have expectations/harrassement/etc. sections. I'm sure those were informed by their own niches.

**Comment by kousu** [comment]
Some potentially overriding CoCs:

* https://etudiant.polymtl.ca/conduite/
* https://etudiant.polymtl.ca/conduite/mission-de-polytechnique-montreal
* https://www.polymtl.ca/livreeuap/docs/documents/code_de_conduite-p278.pdf
* https://share.polymtl.ca/alfresco/service/api/node/content/workspace/SpacesStore/2f35f7a4-f6b2-41ea-9367-0f4b4832a501?a=false&guest=true
* https://share.polymtl.ca/alfresco/service/api/node/content/workspace/SpacesStore/27c5cef2-9269-4396-a3aa-a1f9d3e1c441?a=false&guest=true
* https://share.polymtl.ca/alfresco/service/api/node/content/workspace/SpacesStore/df16b4ff-f416-4247-b720-ea6b064dd779?a=false&guest=true
* https://share.polymtl.ca/alfresco/service/api/node/content/workspace/SpacesStore/e206e8f8-e20e-430c-b7f4-6573b968933b?a=false&guest=true
* https://share.polymtl.ca/alfresco/service/api/node/content/workspace/SpacesStore/72c68731-6108-45c4-ab14-a6f4a2adced6?a=false&guest=true
* https://share.polymtl.ca/alfresco/service/api/node/content/workspace/SpacesStore/c89fca89-be8d-4fe8-a72b-a3c8b9c31e2e?a=false&guest=true
* https://share.polymtl.ca/alfresco/service/api/node/content/workspace/SpacesStore/b63ac475-1f6d-4fea-86d3-39d5b0b325a8?a=false&guest=true

Also this on the wall, that I can't find posted online?

IMG_20211118_175716

**Comment by jcohenadad** [comment]
unfortunately i have other priorities now and i cannot spend more than 2min in choosing/fixing the appropriate CoC-- so i see 2 options:
- @kousu you take the lead and choose what's best
- we merge this so at least we have something (better than nothing) and in the future we improve

**Comment by kousu** [comment]
I would rather not do something as important as a CoC as a throw-away PR like that. Fixing a CoC isn't like fixing a broken link, it's important to get it pretty much right on the first try.

**Pull request closed without merging**
